name: Build Windows App

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.2.0'
      - name: Install dependencies
        run: npm install
      - name: Build win App
        run: npm run package
      - name: Zip the file before upload
        run: |
          Compress-Archive -Path 'release/build/*' -DestinationPath 'win-release.zip'
      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Windows-App
      #     path: win-release.zip
