name: Build Windows App

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.2.0'
      - name: Install dependencies
        run: npm install
      - name: Build win App
        run: npm run package
      - name: Zip the file before upload
        run: |
          Compress-Archive -Path 'release/build/*' -DestinationPath 'win-release.zip'
      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Windows-App
      #     path: win-release.zip
      - name: Create GH Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: win-build-${{ github.run_number }}
          name: Windows Build ${{ github.run_number }}
          files: win-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
